name: Backup PostgreSQL Database

on:
  schedule:
    - cron: '0 */1 * * *' # 
  workflow_dispatch: # Allows manual triggering

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Install PostgreSQL client
      run: sudo apt-get install -y postgresql-client

    - name: Run pg_dump
      env:
        PGHOST: ${{ secrets.PGHOST }}
        PGUSER: ${{ secrets.PGUSER }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
        PGPORT: ${{ secrets.PGPORT }}
      run: |
        pg_dump -h $PGHOST -p $PGPORT -U $PGUSER -d $PGDATABASE > database_backup.sql

    - name: Upload Backup to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: db-backup
        path: database_backup.sql
